import type { Metadata } from "next";
import type { ReactNode } from "react";
import { LegalAside } from "@/components/legal-aside";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = { title: "プライバシーポリシー", description: "くじぐらしが取得・利用する情報、利用目的、外部サービス、保存期間、削除方法をご案内します。", alternates: { canonical: "/privacy" } };
const contents = [{ id: "scope", label: "適用範囲" }, { id: "data", label: "取り扱う情報" }, { id: "ranking", label: "ランキング公開" }, { id: "providers", label: "外部サービス" }, { id: "retention", label: "保有・削除" }, { id: "rights", label: "利用者の権利" }, { id: "ads", label: "広告" }, { id: "contact", label: "お問い合わせ" }] as const;

export default function PrivacyPage() {
  return <><SiteHeader /><main><PageHero title="プライバシーポリシー" description={`施行予定日：アプリ公開日 · 運営者：4L TREE · お問い合わせ：${supportEmail}`} /><div className="mx-auto grid w-full max-w-7xl gap-12 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[minmax(0,1fr)_248px] lg:px-8"><article className="page-prose min-w-0"><Callout>この文書は、公開準備のための公開草案です。アプリ公開前に、実際のSupabaseリージョン、バックアップの保有期間、Googleサービスの設定、アカウント削除手順を確認し、最終版へ更新します。</Callout><h2 id="scope">1. 適用範囲と利用目的</h2><p>4L TREE（以下「運営者」）は、Androidアプリ <b>くじぐらし</b> のゲーム提供、匿名ランキング運営、不正利用・障害の防止、サービス品質の分析、バナー広告の提供に必要な情報を取り扱います。</p><h2 id="data">2. 取り扱う情報</h2><table><thead><tr><th>区分</th><th>取り扱う情報</th><th>目的</th></tr></thead><tbody><tr><td>端末内ゲームデータ</td><td>ゲーム進行、設定、手動選択した数字、統計、チュートリアル、ランキングキャッシュ</td><td>ゲームの保存・復元、画面表示</td></tr><tr><td>匿名ランキングアカウント</td><td>Supabase匿名ユーザーID、認証セッション情報、ニックネーム</td><td>利用者の識別、ランキング・ニックネームの提供、不正送信の防止</td></tr><tr><td>ランキング記録</td><td>ニックネーム、ゲーム内統計、当せん番号、アプリバージョン、送信日時、検証状態</td><td>公開ランキング・最近の記録の表示、記録の検証</td></tr><tr><td>利用・分析情報</td><td>画面閲覧、ゲームイベント、Firebaseインストール識別子、端末関連情報</td><td>サービス品質の分析、機能改善、障害分析</td></tr><tr><td>広告関連情報</td><td>IPアドレス、広告・アプリとの操作、診断情報、広告ID・アプリセットID</td><td>バナー広告の提供、測定、不正広告の防止</td></tr><tr><td>サポート情報</td><td>お問い合わせ時に提供された氏名・メールアドレス・内容・添付画像・端末情報</td><td>お問い合わせへの確認・回答、紛争対応</td></tr></tbody></table><p>運営者は、マイナンバー、決済手段の情報、正確な位置情報をアプリ機能のために直接収集しません。サポートへのお問い合わせには、認証トークン、パスワード、マイナンバー、カード情報を記載しないでください。</p><h2 id="ranking">3. ランキングの公開範囲</h2><p>ランキング機能を利用すると、ニックネームとゲーム内1等記録の一部が他の利用者に公開される場合があります。公開範囲には、ニックネーム、最終ゲーム内収支、当せん時点、抽せん・仮想購入統計、当せん番号、順位、送信日時が含まれる場合があります。ニックネームには、ご本人または第三者の個人情報を入力しないでください。</p><p>ランキングは、実在の宝くじ取引や現実の金銭記録を表示するものではありません。金額・番号・記録はすべてゲーム内で生成される仮想情報です。</p><h2 id="providers">4. 外部サービスと国外での取り扱い</h2><p>アプリ機能のため、Supabase、Firebase、Google Mobile Adsを利用します。ランキングの利用、アプリ分析、リモート設定の取得、広告表示の際に、関連情報が暗号化された通信を通じて各事業者へ送信される場合があります。</p><ul><li><a href="https://supabase.com/privacy">Supabase Privacy Policy</a></li><li><a href="https://firebase.google.com/support/privacy">Firebaseのプライバシーとセキュリティ</a></li><li><a href="https://policies.google.com/privacy?hl=ja">Googleプライバシーポリシー</a></li></ul><p>サービスごとの実際のデータ処理国・リージョンと保有期間は、最終的な公開構成を確認したうえで本ポリシーへ反映します。</p><h2 id="retention">5. 保有期間と削除</h2><p>端末内のゲームデータとキャッシュは、利用者がアプリデータまたはアプリを削除するまで端末に残る場合があります。匿名ランキングアカウント、公開ランキング記録、サポートへのお問い合わせ、バックアップデータの実際の保有期間と削除手順は、公開前の運用設定に基づいて確定し、ご案内します。</p><h2 id="rights">6. 利用者の権利とお問い合わせ</h2><p>利用者は、ご自身の個人情報について、開示、訂正・削除、利用停止などを求めることができます。サポートメールまでご連絡ください。ご本人確認後、関係法令と実際の運用手順に従って対応します。</p><p>アカウント・ランキング記録の削除機能は、現在、公開前の実装・検証項目です。<a href="/delete-account">アカウント・データ削除</a>で現在の状況をご確認ください。</p><h2 id="ads">7. 広告とお子様の情報</h2><p>アプリは、Google Mobile Ads SDKを利用してバナー広告を表示する場合があります。広告SDKは、広告の提供・測定・不正防止のため、端末識別子や広告との操作情報を取り扱う場合があります。同意が必要な地域での同意・撤回手順とお子様向け設定は、実際の公開地域と年齢区分に合わせて公開前に検証します。</p><h2 id="contact">8. お問い合わせと変更</h2><p>個人情報に関するお問い合わせは <a href={`mailto:${supportEmail}`}>{supportEmail}</a> までお送りください。本ポリシーの内容を追加・削除・変更する場合は、アプリまたは本公開ページでお知らせします。</p></article><LegalAside items={contents} /></div></main><SiteFooter /></>;
}

function Callout({ children }: { children: ReactNode }) { return <div className="rounded-xl border border-[#dfb96a] bg-[#fff4d9] p-5 text-[#62450f]"><p className="!m-0 !leading-7 !text-[#62450f]">{children}</p></div>; }
