import type { Metadata } from "next";
import { LegalAside } from "@/components/legal-aside";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = { title: "이용약관", description: "로또 인생 이용약관입니다.", alternates: { canonical: "/terms" } };
const contents = [{ id: "service", label: "서비스 성격" }, { id: "license", label: "이용권·변경" }, { id: "ranking", label: "랭킹·닉네임" }, { id: "records", label: "기록의 이용" }, { id: "external", label: "외부 서비스" }, { id: "conduct", label: "금지 행위" }, { id: "ip", label: "지식재산권" }, { id: "liability", label: "문의" }] as const;

export default function TermsPage() { return <><SiteHeader /><main><PageHero title="이용약관" description="시행 예정일: 앱 공개일 · 운영자: 4L TREE" /><div className="mx-auto grid w-full max-w-6xl gap-12 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[minmax(0,1fr)_248px] lg:px-8"><article className="page-prose min-w-0"><div className="grid grid-cols-[auto_1fr] gap-3 rounded-xl border border-[#e7d49c] bg-[#fff9e7] p-5 text-[#624a00]"><strong>!</strong><p className="!m-0 !leading-7 !text-[#624a00]">이 약관은 Android 앱 로또 인생의 출시 준비용 공개 초안입니다. 실제 배포 전 시행일과 운영 주체 정보를 확정해 갱신합니다.</p></div><h2 id="service">1. 서비스의 성격</h2><p>로또 인생은 복권을 소재로 한 무료 가상 시뮬레이션 게임입니다. 앱 안의 로또 번호, 확률, 금액, 당첨 및 랭킹 기록은 게임 진행을 위한 가상 정보이며 실제 복권의 판매·구매·환전·현금 지급·투자 또는 도박 서비스를 제공하지 않습니다.</p><p>운영자는 동행복권 또는 실제 복권 발행·판매 기관과 제휴하거나 이를 대리하지 않습니다.</p><h2 id="license">2. 이용권과 변경</h2><p>운영자는 이용자에게 개인적이고 비독점적이며 양도할 수 없는 앱 이용권을 부여합니다. 기능 개선, 보안 대응, 법령·정책 변경 또는 기술적 필요에 따라 앱의 전부 또는 일부를 수정·중단할 수 있으며, 이용자 권리에 중대한 영향이 예상되는 경우 합리적인 방법으로 안내합니다.</p><h2 id="ranking">3. 익명 랭킹과 닉네임</h2><p>랭킹 기능은 Supabase 익명 인증을 통해 기기별 익명 계정을 생성하거나 복원할 수 있습니다. 별도의 이메일·전화번호 로그인을 요구하지 않을 수 있으나 앱 삭제·기기 변경·데이터 초기화에 따라 계정 복원이 제한될 수 있습니다.</p><p>닉네임에는 본인 또는 타인의 개인정보, 사칭, 욕설·음란·차별 표현, 운영 방해 표현을 사용할 수 없습니다. 운영자는 운영 기준에 위반되는 닉네임이나 기록을 수정·비공개·삭제하거나 랭킹 이용을 제한할 수 있습니다.</p><h2 id="records">4. 기록의 이용과 공정성</h2><p>1등 달성 기록은 검증 절차를 거쳐 전체 랭킹, 최근 당첨자 또는 개인 기록에 표시될 수 있습니다. 운영자는 공정성과 안정성을 위해 앱 버전, 게임 진행 통계, 제출 횟수, 세션 정보 등을 검증할 수 있습니다. 변조된 앱, 자동화 도구, 비정상 요청 등 부정한 방법으로 생성된 기록은 거부·삭제·검토 대기 처리될 수 있습니다.</p><h2 id="external">5. 광고와 외부 서비스</h2><p>앱은 Google Mobile Ads SDK를 통한 광고를 포함할 수 있고, Firebase 및 Supabase 등 외부 서비스를 이용할 수 있습니다. 외부 서비스의 처리 내용은 <a href="/privacy">개인정보처리방침</a>과 각 서비스 제공자의 정책에 따릅니다.</p><h2 id="conduct">6. 이용자의 금지 행위</h2><ul><li>관계 법령 또는 이 약관을 위반하는 행위</li><li>앱·서버·랭킹 API의 정상 운영을 방해하거나 우회하는 행위</li><li>프로그램 변조, 리버스 엔지니어링, 자동화·봇 사용, 비정상 트래픽 발생 행위</li><li>타인의 정보·계정을 도용하거나 개인정보를 침해하는 행위</li><li>닉네임, 공유 이미지 또는 문의를 이용해 타인을 비방·사칭·괴롭히는 행위</li></ul><h2 id="ip">7. 지식재산권</h2><p>앱의 소프트웨어와 콘텐츠에 관한 권리는 운영자 또는 정당한 권리자에게 귀속됩니다. 오픈소스 구성요소는 각 라이선스 조건에 따릅니다.</p><h2 id="liability">8. 책임의 제한 및 문의</h2><p>법령이 허용하는 범위에서 앱 중단, 데이터 손실, 광고·외부 서비스 장애에 대한 책임을 제한합니다. 다만 운영자의 고의·중대한 과실 및 법령상 제한할 수 없는 책임에는 적용되지 않습니다. 문의는 <a href={`mailto:${supportEmail}`}>{supportEmail}</a> 또는 <a href="/support">고객지원 페이지</a>로 접수할 수 있습니다.</p></article><LegalAside items={contents} /></div></main><SiteFooter /></>; }
