import type { Metadata } from "next";
import { LegalAside } from "@/components/legal-aside";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = { title: "利用規約", description: "くじぐらしのサービス内容、ランキング、禁止事項、責任範囲に関する利用条件。", alternates: { canonical: "/terms" } };
const contents = [{ id: "service", label: "サービスの性質" }, { id: "license", label: "利用権・変更" }, { id: "ranking", label: "ランキング" }, { id: "records", label: "記録の利用" }, { id: "external", label: "外部サービス" }, { id: "conduct", label: "禁止事項" }, { id: "ip", label: "知的財産権" }, { id: "liability", label: "責任・お問い合わせ" }] as const;

export default function TermsPage() {
  return <><SiteHeader /><main><PageHero title="利用規約" description="施行予定日：アプリ公開日 · 運営者：4L TREE" /><div className="mx-auto grid w-full max-w-7xl gap-12 px-4 py-12 sm:px-6 sm:py-16 lg:grid-cols-[minmax(0,1fr)_248px] lg:px-8"><article className="page-prose min-w-0"><div className="rounded-xl border border-[#dfb96a] bg-[#fff4d9] p-5 text-[#62450f]"><p className="!m-0 !leading-7 !text-[#62450f]">本規約は、Androidアプリ「くじぐらし」の公開準備用草案です。実際の配信前に、施行日と運営主体に関する情報を確定し、更新します。</p></div><h2 id="service">1. サービスの性質</h2><p>くじぐらしは、数字くじを題材とした仮想シミュレーションゲームです。アプリ内の番号、確率、金額、当せん、ランキング記録はゲーム進行のための仮想情報であり、実在する宝くじの販売・購入・換金、現金の支払い、投資または賭博サービスを提供するものではありません。</p><p>運営者は、実在する宝くじの発行・販売事業者と提携せず、これらを代理しません。</p><h2 id="license">2. 利用権と変更</h2><p>運営者は、利用者に対し、個人的、非独占的かつ譲渡できないアプリ利用権を付与します。機能改善、セキュリティ対応、法令・ポリシーの変更または技術上の必要により、アプリの全部または一部を変更・中断する場合があります。利用者の権利に重大な影響が見込まれる場合は、合理的な方法でお知らせします。</p><h2 id="ranking">3. 匿名ランキングとニックネーム</h2><p>ランキング機能は、Supabaseの匿名認証により、端末ごとの匿名アカウントを作成または復元する場合があります。メールアドレス・電話番号によるログインを求めない場合がありますが、アプリの削除、端末の変更、データの初期化により、アカウントを復元できないことがあります。</p><p>ニックネームには、ご本人または第三者の個人情報、なりすまし、暴言・わいせつ・差別表現、運営を妨げる表現を使用できません。運営者は、運営基準に違反するニックネームや記録を修正・非公開・削除し、またはランキングの利用を制限する場合があります。</p><h2 id="records">4. 記録の利用と公平性</h2><p>ゲーム内1等の達成記録は、検証後に総合ランキング、最近の達成者、個人記録へ表示される場合があります。運営者は、公平性と安定性のため、アプリバージョン、ゲーム進行統計、送信回数、セッション情報などを検証する場合があります。改変されたアプリ、自動化ツール、不正なリクエストなどで生成された記録は、拒否・削除・審査待ちとする場合があります。</p><h2 id="external">5. 広告と外部サービス</h2><p>アプリは、Google Mobile Ads SDKによる広告を含む場合があり、Firebase、Supabaseなどの外部サービスを利用する場合があります。外部サービスによる情報の取り扱いは、<a href="/privacy">プライバシーポリシー</a>および各サービス事業者のポリシーに従います。</p><h2 id="conduct">6. 禁止事項</h2><ul><li>関係法令または本規約に違反する行為</li><li>アプリ、サーバー、ランキングAPIの正常な運営を妨げ、または回避する行為</li><li>プログラムの改変、リバースエンジニアリング、自動化・ボットの使用、不正なトラフィックを発生させる行為</li><li>第三者の情報・アカウントを盗用し、個人情報を侵害する行為</li><li>ニックネーム、共有画像またはお問い合わせを利用して、第三者を誹謗・なりすまし・嫌がらせする行為</li></ul><h2 id="ip">7. 知的財産権</h2><p>アプリのソフトウェアおよびコンテンツに関する権利は、運営者または正当な権利者に帰属します。オープンソースの構成要素は、それぞれのライセンス条件に従います。</p><h2 id="liability">8. 責任の制限とお問い合わせ</h2><p>法令で認められる範囲において、アプリの中断、データの喪失、広告・外部サービスの障害に関する責任を制限します。ただし、運営者の故意・重過失および法令上制限できない責任には適用しません。お問い合わせは <a href={`mailto:${supportEmail}`}>{supportEmail}</a> または <a href="/support">サポートページ</a>からお送りいただけます。</p></article><LegalAside items={contents} /></div></main><SiteFooter /></>;
}
