import type { Metadata } from "next";
import type { ReactNode } from "react";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = { title: "고객지원", description: "로또 인생 고객지원 안내입니다.", alternates: { canonical: "/support" } };

export default function SupportPage() {
  return <><SiteHeader /><main><PageHero title="도움이 필요하신가요?" description="앱 사용, 광고, 랭킹, 개인정보 관련 문의를 편하게 보내 주세요." /><section className="mx-auto w-full max-w-6xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl border border-slate-200 bg-white p-7"><p className="text-xs font-black tracking-[.1em] text-lotto-violet">CONTACT</p><h2 className="mt-2 text-2xl font-black tracking-[-.05em]">이메일 고객지원</h2><p className="mt-3 leading-7 text-slate-600">문의 내용을 확인해 필요한 범위에서 답변드리겠습니다. 인증 토큰, 비밀번호, 주민등록번호, 신용카드 정보는 보내지 마세요.</p><a href={`mailto:${supportEmail}?subject=%5B%EB%A1%9C%EB%98%90%20%EC%9D%B8%EC%83%9D%20%EB%AC%B8%EC%9D%98%5D`} className="mt-4 inline-block text-lg font-black text-lotto-violet hover:text-lotto-blue">{supportEmail}</a><ul className="mt-5 divide-y divide-slate-100"><SupportItem>앱 실행·화면 표시·게임 저장 문제</SupportItem><SupportItem>배너 광고가 화면을 가리거나 비정상 표시되는 문제</SupportItem><SupportItem>익명 랭킹·닉네임·기록 표시와 제출 문제</SupportItem><SupportItem>개인정보 열람·정정·삭제·처리정지 요청</SupportItem></ul></article><article className="rounded-2xl border border-slate-200 bg-white p-7"><p className="text-xs font-black tracking-[.1em] text-lotto-violet">FAQ</p><h2 className="mt-2 text-2xl font-black tracking-[-.05em]">자주 묻는 질문</h2><Faq question="게임 진행을 처음부터 시작하고 싶어요.">앱 설정의 진행 초기화는 기기에 저장된 게임 진행 데이터를 초기화합니다. Supabase 익명 계정과 이미 제출된 공개 랭킹 기록의 삭제를 보장하지는 않습니다.</Faq><Faq question="랭킹이 바로 갱신되지 않아요.">네트워크 상태와 캐시 정책에 따라 이전 기록을 먼저 보여줄 수 있습니다. 문제가 계속되면 닉네임, 발생 시간, 화면 캡처를 함께 보내 주세요.</Faq><Faq question="광고 관련 문의는 어떻게 하나요?">광고가 앱을 가리거나 반복적으로 비정상 표시되는 경우, 광고 화면과 기기 정보를 함께 보내 주세요. 광고 소재 자체의 내용은 광고 제공자가 관리합니다.</Faq><Faq question="계정이나 개인정보를 삭제하고 싶어요.">익명 계정·랭킹 기록 삭제 기능은 출시 전 구현·검증 대상입니다. 현재 상태는 계정 및 데이터 삭제 안내에서 확인할 수 있습니다.</Faq></article></div><div className="mt-16 max-w-2xl"><p className="text-xs font-black tracking-[.1em] text-lotto-violet">문의 템플릿</p><h2 className="mt-2 text-3xl font-black tracking-[-.06em]">이 정보를 함께 보내 주세요.</h2><p className="mt-3 text-slate-500">필수 항목은 아니며, 문제 확인에 도움이 되는 범위에서만 작성해 주세요.</p><pre className="mt-5 overflow-x-auto rounded-xl bg-slate-100 p-5 text-sm leading-6 text-slate-700">{`[로또 인생 문의]\n문의 유형: 오류 / 광고 / 랭킹 / 개인정보 / 기타\n닉네임: (랭킹 이용 시에만)\n앱 버전:\n휴대전화 모델·Android 버전:\n문제가 발생한 날짜와 시간:\n재현 방법 또는 상세 설명:\n화면 캡처: (가능하면 첨부)`}</pre></div></section></main><SiteFooter /></>;
}

function SupportItem({ children }: { children: ReactNode }) { return <li className="flex gap-3 py-3 text-sm text-slate-600 before:content-['✓'] before:font-black before:text-emerald-600">{children}</li>; }
function Faq({ question, children }: { question: string; children: ReactNode }) { return <details className="border-b border-slate-100 py-5 first:mt-3"><summary className="cursor-pointer font-extrabold text-lotto-navy">{question}</summary><p className="mt-3 leading-7 text-slate-500">{children}</p></details>; }
