import type { Metadata } from "next";
import type { ReactNode } from "react";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { supportEmail } from "@/lib/site";

export const metadata: Metadata = { title: "サポート", description: "くじぐらしの不具合、広告、ランキング、アカウントとデータの削除に関するお問い合わせとよくあるご質問。", alternates: { canonical: "/support" } };

export default function SupportPage() {
  return <><SiteHeader /><main><PageHero title="お困りですか？" description="アプリの動作、広告、ランキング、プライバシーに関するご質問をお送りください。" /><section className="mx-auto w-full max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl border border-[#e4d5b7] bg-white p-7"><p className="eyebrow">CONTACT</p><h2 className="mt-2 text-2xl font-black tracking-[-.05em]">メールサポート</h2><p className="mt-3 leading-7 text-[#685744]">内容を確認し、必要な範囲でご案内します。認証トークン、パスワード、マイナンバー、クレジットカード情報は送信しないでください。</p><a href={`mailto:${supportEmail}?subject=%E3%80%90%E3%81%8F%E3%81%98%E3%81%90%E3%82%89%E3%81%97%E3%80%91%E3%81%8A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B`} className="mt-4 inline-block break-all text-lg font-black text-[#b71912] hover:text-[#75100c]">{supportEmail}</a><ul className="mt-5 divide-y divide-[#f0e6d2]"><SupportItem>アプリの起動・画面表示・ゲーム保存に関する問題</SupportItem><SupportItem>広告が画面を隠す、または正しく表示されない問題</SupportItem><SupportItem>匿名ランキング・ニックネーム・記録表示や送信の問題</SupportItem><SupportItem>個人情報の開示・訂正・削除・利用停止のご依頼</SupportItem></ul></article><article className="rounded-2xl border border-[#e4d5b7] bg-white p-7"><p className="eyebrow">FAQ</p><h2 className="mt-2 text-2xl font-black tracking-[-.05em]">よくあるご質問</h2><Faq question="ゲームを最初からやり直したいです。">アプリ設定の進行リセットは、端末に保存されたゲームデータを初期化します。Supabaseの匿名アカウントや、すでに送信された公開ランキング記録の削除を保証するものではありません。</Faq><Faq question="ランキングがすぐに更新されません。">通信状況やキャッシュにより、以前の記録が先に表示されることがあります。問題が続く場合は、ニックネーム、発生日時、画面のスクリーンショットをお送りください。</Faq><Faq question="広告について問い合わせたいです。">広告がアプリ画面を隠す、または繰り返し正しく表示されない場合は、広告画面と端末情報をお送りください。広告素材の内容は広告配信事業者が管理しています。</Faq><Faq question="アカウントや個人情報を削除したいです。">匿名アカウントとランキング記録の削除機能は、公開前の実装・検証項目です。現在の状況は「アカウント・データ削除」でご確認ください。</Faq></article></div><div className="mt-16 max-w-2xl"><p className="eyebrow">MESSAGE TEMPLATE</p><h2 className="mt-2 text-3xl font-black tracking-[-.06em]">次の情報を添えてください。</h2><p className="mt-3 text-[#715c45]">必須ではありません。問題の確認に役立つ範囲でご記入ください。</p><pre className="mt-5 overflow-x-auto rounded-xl bg-[#f2eadb] p-5 text-sm leading-6 text-[#534331]">{`【くじぐらし お問い合わせ】\nお問い合わせ種別：不具合 / 広告 / ランキング / 個人情報 / その他\nニックネーム：（ランキング利用時のみ）\nアプリバージョン：\n端末機種・Androidバージョン：\n発生日時：\n再現方法・詳しい内容：\n画面のスクリーンショット：（可能であれば添付）`}</pre></div></section></main><SiteFooter /></>;
}

function SupportItem({ children }: { children: ReactNode }) { return <li className="py-3 text-sm leading-6 text-[#685744]">{children}</li>; }
function Faq({ question, children }: { question: string; children: ReactNode }) { return <details className="border-b border-[#f0e6d2] py-5 first:mt-3"><summary className="cursor-pointer font-extrabold text-[#281407]">{question}</summary><p className="mt-3 leading-7 text-[#715c45]">{children}</p></details>; }
